{{- if .Values.webhook.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logrix.fullname" . }}-webhook
  labels:
    {{- include "logrix.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  replicas: {{ .Values.webhook.replicaCount }}
  selector:
    matchLabels:
      {{- include "logrix.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: webhook
  template:
    metadata:
      labels:
        {{- include "logrix.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: webhook
    spec:
      serviceAccountName: {{ include "logrix.serviceAccountName" . }}
      containers:
        - name: webhook
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["logrix", "webhook-dispatcher"]
          envFrom:
            - configMapRef:
                name: {{ include "logrix.fullname" . }}-config
          resources:
            {{- toYaml .Values.webhook.resources | nindent 12 }}
{{- end }}
