{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logrix.fullname" . }}-api
  labels:
    {{- include "logrix.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
{{- if not .Values.api.hpa.enabled }}
  replicas: {{ .Values.api.replicas }}
{{- end }}
  selector:
    matchLabels:
      {{- include "logrix.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "logrix.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      serviceAccountName: {{ include "logrix.serviceAccountName" . }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["logrix", "api", "--port", "{{ .Values.api.port }}"]
          ports:
            - name: graphql
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "logrix.fullname" . }}-config
            {{- if .Values.config.existingSecret }}
            - secretRef:
                name: {{ .Values.config.existingSecret }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: graphql
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: graphql
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          {{- if or .Values.config.manifestContent .Values.config.schemaContent }}
          volumeMounts:
            - name: logrix-config-volume
              mountPath: /etc/logrix
          {{- end }}
      {{- if or .Values.config.manifestContent .Values.config.schemaContent }}
      volumes:
        - name: logrix-config-volume
          configMap:
            name: {{ include "logrix.fullname" . }}-config
            items:
              {{- if .Values.config.manifestContent }}
              - key: manifest.yaml
                path: manifest.yaml
              {{- end }}
              {{- if .Values.config.schemaContent }}
              - key: schema.graphql
                path: schema.graphql
              {{- end }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "logrix.fullname" . }}-api
  labels:
    {{- include "logrix.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: graphql
      protocol: TCP
      name: graphql
  selector:
    {{- include "logrix.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}
