{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "logrix.fullname" . }}-api-pdb
  labels:
    {{- include "logrix.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "logrix.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "logrix.fullname" . }}-ingester-pdb
  labels:
    {{- include "logrix.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingester
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "logrix.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ingester
{{- end }}
