apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logrix-dev

resources:
  - namespace.yaml
  - ../base
  - postgres.yaml
  - rabbitmq.yaml

secretGenerator:
  - name: logrix-secrets
    literals:
      - DATABASE_URL=postgres://logrix:logrix@postgres:5432/logrix
      - RABBITMQ_URL=amqp://logrix:logrix@rabbitmq:5672
