apiVersion: v2
name: logrix
description: High-performance, modular blockchain indexer for EVM chains
type: application
version: 0.3.0
appVersion: "0.3.0"
keywords:
  - blockchain
  - ethereum
  - indexer
  - graphql
  - evm
  - keda
maintainers:
  - name: Vishal
    url: https://github.com/Vishal-770/Logrix
