import { Command } from "commander";
import * as fs from "fs";
import * as path from "path";
import { parse as parseYaml } from "yaml";

// ---------------------------------------------------------------------------
// Type definitions for logrix.yaml structure
// ---------------------------------------------------------------------------

interface AbiRef {
  name: string;
  file: string;
}

interface EventHandler {
  event: string;
  handler: string;
}

interface Mapping {
  abis: AbiRef[];
  eventHandlers: EventHandler[];
}

interface DataSource {
  name: string;
  source: {
    abi: string;
  };
  mapping: Mapping;
}

interface LogrixConfig {
  dataSources: DataSource[];
}

// ---------------------------------------------------------------------------
// ABI types
// ---------------------------------------------------------------------------

interface AbiInput {
  name: string;
  type: string;
  indexed?: boolean;
}

interface AbiEvent {
  name: string;
  type: string;
  inputs: AbiInput[];
}

// ---------------------------------------------------------------------------
// Code generators
// ---------------------------------------------------------------------------

function solTypeToAs(solType: string): string {
  if (solType === "address") return "string";
  if (solType === "bool") return "bool";
  if (solType.startsWith("uint") || solType.startsWith("int")) return "string"; // large ints as string
  if (solType === "bytes32" || solType === "bytes") return "string";
  if (solType === "string") return "string";
  return "string";
}

function generateEventsTs(dataSources: DataSource[], projectDir: string): string {
  const lines: string[] = [
    "// Auto-generated by `logrix codegen`. Do not edit.",
    'import { EventLog } from "@logrix/sdk";',
    "",
  ];

  for (const ds of dataSources) {
    for (const abiRef of ds.mapping.abis) {
      const abiPath = path.resolve(projectDir, abiRef.file);
      if (!fs.existsSync(abiPath)) {
        console.warn(`  Warning: ABI file not found: ${abiRef.file}`);
        continue;
      }
      const rawAbi: AbiEvent[] = JSON.parse(fs.readFileSync(abiPath, "utf-8"));
      const events = rawAbi.filter((x) => x.type === "event");

      for (const ev of events) {
        const paramsClass = `${ev.name}Params`;
        const eventClass = `${ev.name}Event`;

        // Params class
        lines.push(`export class ${paramsClass} {`);
        for (const inp of ev.inputs) {
          lines.push(`  ${inp.name}: ${solTypeToAs(inp.type)} = "";`);
        }
        lines.push("");
        lines.push(`  constructor(raw: EventLog) {`);
        let topicIdx = 1;
        for (const inp of ev.inputs) {
          if (inp.indexed) {
            lines.push(
              `    this.${inp.name} = raw.topics.length > ${topicIdx} ? raw.topics[${topicIdx}] : "";`
            );
            topicIdx++;
          } else {
            lines.push(`    this.${inp.name} = raw.data;`);
          }
        }
        lines.push("  }");
        lines.push("}");
        lines.push("");

        // Event class
        lines.push(`export class ${eventClass} {`);
        lines.push("  address: string;");
        lines.push("  blockNumber: u64;");
        lines.push("  blockHash: string;");
        lines.push("  transactionHash: string;");
        lines.push("  logIndex: u32;");
        lines.push("  blockTimestamp: u64;");
        lines.push(`  params: ${paramsClass};`);
        lines.push("");
        lines.push("  constructor(raw: EventLog) {");
        lines.push("    this.address = raw.address;");
        lines.push("    this.blockNumber = raw.block_number;");
        lines.push("    this.blockHash = raw.block_hash;");
        lines.push("    this.transactionHash = raw.transaction_hash;");
        lines.push("    this.logIndex = raw.log_index;");
        lines.push("    this.blockTimestamp = raw.block_timestamp;");
        lines.push(`    this.params = new ${paramsClass}(raw);`);
        lines.push("  }");
        lines.push("}");
        lines.push("");
      }
    }
  }

  return lines.join("\n");
}

interface SchemaField {
  name: string;
  type: string;
  required: boolean;
}

function parseSchemaFields(body: string): SchemaField[] {
  const fields: SchemaField[] = [];
  for (const rawLine of body.split("\n")) {
    const line = rawLine.replace(/@\w+(\([^)]*\))?/g, "").trim();
    if (!line || line.startsWith("#")) continue;
    const colonIdx = line.indexOf(":");
    if (colonIdx === -1) continue;
    const name = line.slice(0, colonIdx).trim();
    const typePart = line.slice(colonIdx + 1).trim();
    const required = typePart.endsWith("!");
    const type = typePart.replace("!", "").trim();
    fields.push({ name, type, required });
  }
  return fields;
}

function graphqlTypeToAs(gqlType: string): string {
  if (gqlType === "ID" || gqlType === "String" || gqlType === "Bytes") return "string";
  if (gqlType === "Int") return "i32";
  if (gqlType === "BigInt") return "u64";
  if (gqlType === "Boolean") return "bool";
  if (gqlType === "Float") return "f64";
  return "string";
}

function generateSchemaTs(projectDir: string): string {
  const schemaPath = path.join(projectDir, "schema.graphql");
  const lines: string[] = [
    "// Auto-generated by `logrix codegen`. Do not edit.",
    'import { logrix_emit, logrix_db_get, logrix_db_set } from "@logrix/sdk";',
    "",
  ];

  if (!fs.existsSync(schemaPath)) {
    console.warn("  Warning: schema.graphql not found, skipping entity generation.");
    return lines.join("\n");
  }

  const content = fs.readFileSync(schemaPath, "utf-8");
  const entityRegex = /type\s+(\w+)\s+@entity\s*\{([^}]+)\}/g;
  let match: RegExpExecArray | null;

  while ((match = entityRegex.exec(content)) !== null) {
    const entityName = match[1];
    const fields = parseSchemaFields(match[2]);

    lines.push(`export class ${entityName} {`);
    for (const f of fields) {
      if (f.name === "id") {
        lines.push("  id: string;");
      } else {
        const asType = graphqlTypeToAs(f.type);
        const defaultVal =
          asType === "string" ? '""'
          : asType === "bool" ? "false"
          : asType === "f64" ? "0.0"
          : "0";
        lines.push(`  ${f.name}: ${asType} = ${defaultVal};`);
      }
    }
    lines.push("");
    lines.push("  constructor(id: string) {");
    lines.push("    this.id = id;");
    lines.push("  }");
    lines.push("");
    lines.push("  save(): void {");
    // Build JSON payload string
    const jsonParts: string[] = [];
    for (const f of fields) {
      const asType = graphqlTypeToAs(f.type);
      const isNum = asType !== "string" && asType !== "bool";
      const isStr = asType === "string";
      if (isStr) {
        jsonParts.push(`"\\"${f.name}\\":\\"" + this.${f.name} + "\\""`);
      } else {
        jsonParts.push(`"\\"${f.name}\\":" + this.${f.name}.toString()`);
      }
    }
    lines.push(`    const payload = "{" + ${jsonParts.join(' + "," + ')} + "}";`);
    lines.push(`    logrix_emit("${entityName}", payload);`);
    lines.push("  }");
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Command
// ---------------------------------------------------------------------------

export function codegenCommand(): Command {
  const cmd = new Command("codegen");

  cmd
    .description("Generate typed AssemblyScript bindings from ABI files and schema.graphql")
    .action(() => {
      const projectDir = process.cwd();
      const configPath = path.join(projectDir, "logrix.yaml");

      if (!fs.existsSync(configPath)) {
        console.error("Error: logrix.yaml not found. Run this command from your project root.");
        process.exit(1);
      }

      const config: LogrixConfig = parseYaml(
        fs.readFileSync(configPath, "utf-8")
      ) as LogrixConfig;

      const generatedDir = path.join(projectDir, "src", "generated");
      fs.mkdirSync(generatedDir, { recursive: true });

      console.log("Generating src/generated/events.ts ...");
      const eventsTs = generateEventsTs(config.dataSources, projectDir);
      fs.writeFileSync(path.join(generatedDir, "events.ts"), eventsTs);

      console.log("Generating src/generated/schema.ts ...");
      const schemaTs = generateSchemaTs(projectDir);
      fs.writeFileSync(path.join(generatedDir, "schema.ts"), schemaTs);

      console.log("Done.");
    });

  return cmd;
}
