import { Command } from "commander";
import * as fs from "fs";
import * as path from "path";
import { parse as parseYaml } from "yaml";

// ---------------------------------------------------------------------------
// Type definitions for logrix.yaml structure
// ---------------------------------------------------------------------------

interface AbiRef {
  name: string;
  file: string;
}

interface EventHandler {
  event: string;
  handler: string;
}

interface Mapping {
  abis: AbiRef[];
  eventHandlers: EventHandler[];
}

interface DataSource {
  name: string;
  source: {
    address?: string;
    abi: string;
    startBlock?: number;
  };
  mapping: Mapping;
}

interface LogrixConfig {
  specVersion?: string;
  network?: {
    name?: string;
    chainId?: number;
    rpcUrl?: string;
  };
  dataSources: DataSource[];
}

// ---------------------------------------------------------------------------
// ABI types
// ---------------------------------------------------------------------------

interface AbiInput {
  name: string;
  type: string;
  indexed?: boolean;
}

interface AbiEvent {
  name: string;
  type: string;
  inputs: AbiInput[];
}

// ---------------------------------------------------------------------------
// Code generators
// ---------------------------------------------------------------------------

function solTypeToAs(solType: string): string {
  if (solType === "address") return "Address";
  if (solType === "bool") return "bool";
  if (solType.startsWith("uint") || solType.startsWith("int")) return "BigInt";
  if (solType === "bytes32" || solType === "bytes") return "Bytes";
  if (solType === "string") return "string";
  return "string";
}

function generateEventsTs(dataSources: DataSource[], projectDir: string): string {
  const lines: string[] = [
    "// Auto-generated by `logrix codegen`. Do not edit.",
    'import { EventLog, BigInt, Address, Bytes, decodeDynamicString, decodeDynamicBytes } from "@logrix/sdk";',
    "",
  ];

  // Contract address constants for multi-contract indexers
  lines.push("// ---------------------------------------------------------------------------");
  lines.push("// Multi-Contract Address Constants");
  lines.push("// ---------------------------------------------------------------------------");
  for (const ds of dataSources) {
    const constName = `${ds.name.toUpperCase()}_ADDRESS`;
    const addr = ds.source?.address?.toLowerCase() || "0x0000000000000000000000000000000000000000";
    lines.push(`export const ${constName}: string = "${addr}";`);
  }
  lines.push("");

  // Multi-contract event routing helper
  lines.push("/** Helper to verify if an event belongs to a target contract address */");
  lines.push("export function isFromContract(raw: EventLog, targetAddress: string): bool {");
  lines.push("  return raw.address.toLowerCase() == targetAddress.toLowerCase();");
  lines.push("}");
  lines.push("");

  const seenEventNames = new Set<string>();

  for (const ds of dataSources) {
    if (!ds.mapping || !ds.mapping.abis) continue;

    for (const abiRef of ds.mapping.abis) {
      const abiPath = path.resolve(projectDir, abiRef.file);
      if (!fs.existsSync(abiPath)) {
        console.warn(`  Warning: ABI file not found: ${abiRef.file}`);
        continue;
      }

      let rawAbi: AbiEvent[];
      try {
        rawAbi = JSON.parse(fs.readFileSync(abiPath, "utf-8"));
      } catch (e: any) {
        console.warn(`  Warning: Failed to parse ABI ${abiRef.file}: ${e.message}`);
        continue;
      }

      const events = Array.isArray(rawAbi) ? rawAbi.filter((x) => x.type === "event") : [];

      for (const ev of events) {
        const scopedParamsClass = `${ds.name}_${ev.name}Params`;
        const scopedEventClass = `${ds.name}_${ev.name}Event`;
        const isFirstOccurrence = !seenEventNames.has(ev.name);
        seenEventNames.add(ev.name);

        // Params class
        lines.push(`export class ${scopedParamsClass} {`);
        for (const inp of ev.inputs) {
          const asType = solTypeToAs(inp.type);
          const defaultVal =
            asType === "Address"
              ? 'Address.fromString("0x0000000000000000000000000000000000000000")'
              : asType === "Bytes"
              ? 'Bytes.fromHexString("0x")'
              : asType === "BigInt"
              ? "BigInt.zero()"
              : asType === "bool"
              ? "false"
              : '""';
          lines.push(`  ${inp.name}: ${asType} = ${defaultVal};`);
        }
        lines.push("");
        lines.push(`  constructor(raw: EventLog) {`);
        let topicIdx = 1;
        let nonIndexedIdx = 0;
        for (const inp of ev.inputs) {
          const asType = solTypeToAs(inp.type);
          if (inp.indexed) {
            const readTopic = `raw.topics.length > ${topicIdx} ? raw.topics[${topicIdx}] : ""`;
            if (asType === "BigInt") {
              lines.push(`    this.${inp.name} = BigInt.fromString(${readTopic});`);
            } else if (asType === "Address") {
              lines.push(`    this.${inp.name} = Address.fromString(${readTopic});`);
            } else if (asType === "Bytes") {
              lines.push(`    this.${inp.name} = Bytes.fromHexString(${readTopic});`);
            } else {
              lines.push(`    this.${inp.name} = ${readTopic};`);
            }
            topicIdx++;
          } else {
            if (inp.type === "string") {
              lines.push(`    this.${inp.name} = decodeDynamicString(raw.data, ${nonIndexedIdx});`);
            } else if (inp.type === "bytes") {
              lines.push(`    this.${inp.name} = decodeDynamicBytes(raw.data, ${nonIndexedIdx});`);
            } else {
              lines.push(`    {`);
              lines.push(`      const dataHex = raw.data.startsWith("0x") ? raw.data.slice(2) : raw.data;`);
              lines.push(`      const offset = ${nonIndexedIdx * 64};`);
              lines.push(
                `      const rawWord = dataHex.length >= offset + 64 ? "0x" + dataHex.slice(offset, offset + 64) : (offset == 0 ? raw.data : "");`
              );
              if (asType === "BigInt") {
                lines.push(`      this.${inp.name} = BigInt.fromString(rawWord);`);
              } else if (asType === "Address") {
                lines.push(`      this.${inp.name} = Address.fromString(rawWord);`);
              } else if (asType === "Bytes") {
                lines.push(`      this.${inp.name} = Bytes.fromHexString(rawWord);`);
              } else {
                lines.push(`      this.${inp.name} = rawWord;`);
              }
              lines.push(`    }`);
            }
            nonIndexedIdx++;
          }
        }
        lines.push("  }");
        lines.push("}");
        lines.push("");

        // Event class
        lines.push(`export class ${scopedEventClass} {`);
        lines.push("  address: Address;");
        lines.push("  blockNumber: BigInt;");
        lines.push("  blockHash: string;");
        lines.push("  transactionHash: string;");
        lines.push("  logIndex: u32;");
        lines.push("  blockTimestamp: BigInt;");
        lines.push(`  params: ${scopedParamsClass};`);
        lines.push("");
        lines.push("  constructor(raw: EventLog) {");
        lines.push("    this.address = Address.fromString(raw.address);");
        lines.push("    this.blockNumber = BigInt.fromU64(raw.block_number);");
        lines.push("    this.blockHash = raw.block_hash;");
        lines.push("    this.transactionHash = raw.transaction_hash;");
        lines.push("    this.logIndex = raw.log_index;");
        lines.push("    this.blockTimestamp = BigInt.fromU64(raw.block_timestamp);");
        lines.push(`    this.params = new ${scopedParamsClass}(raw);`);
        lines.push("  }");
        lines.push("}");
        lines.push("");

        // Export convenience aliases if this is the primary occurrence
        if (isFirstOccurrence) {
          lines.push(`export { ${scopedParamsClass} as ${ev.name}Params };`);
          lines.push(`export { ${scopedEventClass} as ${ev.name}Event };`);
          lines.push("");
        }
      }
    }
  }

  return lines.join("\n");
}

interface SchemaField {
  name: string;
  type: string;
  required: boolean;
  isDerived: boolean;
  derivedField?: string;
}

function parseSchemaFields(body: string): SchemaField[] {
  const fields: SchemaField[] = [];
  for (const rawLine of body.split("\n")) {
    const trimmed = rawLine.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    // Detect @derivedFrom(field: "...")
    const isDerived = trimmed.includes("@derivedFrom");
    let derivedField: string | undefined;
    if (isDerived) {
      const match = /@derivedFrom\s*\(\s*field\s*:\s*["']([^"']+)["']\s*\)/.exec(trimmed);
      if (match) {
        derivedField = match[1];
      }
    }

    const cleanLine = trimmed.replace(/@\w+(\([^)]*\))?/g, "").trim();
    const colonIdx = cleanLine.indexOf(":");
    if (colonIdx === -1) continue;
    const name = cleanLine.slice(0, colonIdx).trim();
    const typePart = cleanLine.slice(colonIdx + 1).trim();
    const required = typePart.endsWith("!");
    const type = typePart.replace("!", "").trim();
    fields.push({ name, type, required, isDerived, derivedField });
  }
  return fields;
}

function graphqlTypeToAs(gqlType: string): string {
  if (gqlType === "ID" || gqlType === "String" || gqlType === "Bytes") return "string";
  if (gqlType === "Int") return "i32";
  if (gqlType === "BigInt") return "BigInt";
  if (gqlType === "Boolean") return "bool";
  if (gqlType === "Float") return "f64";
  return "string";
}

function generateSchemaTs(projectDir: string): string {
  const schemaPath = path.join(projectDir, "schema.graphql");
  const lines: string[] = [
    "// Auto-generated by `logrix codegen`. Do not edit.",
    'import { store, BigInt, extractJsonField } from "@logrix/sdk";',
    "",
  ];

  if (!fs.existsSync(schemaPath)) {
    console.warn("  Warning: schema.graphql not found, skipping entity generation.");
    return lines.join("\n");
  }

  const content = fs.readFileSync(schemaPath, "utf-8");
  const entityRegex = /type\s+(\w+)\s+@entity\s*\{([^}]+)\}/g;
  let match: RegExpExecArray | null;

  while ((match = entityRegex.exec(content)) !== null) {
    const entityName = match[1];
    const fields = parseSchemaFields(match[2]);

    lines.push(`export class ${entityName} {`);
    for (const f of fields) {
      if (f.name === "id") {
        lines.push("  id: string;");
      } else if (f.isDerived) {
        // Virtual reverse-lookup field; not stored directly in DB payload
        lines.push(`  // @derivedFrom(field: "${f.derivedField || ""}") virtual relation`);
      } else {
        const asType = graphqlTypeToAs(f.type);
        const defaultVal =
          asType === "string" ? '""'
          : asType === "BigInt" ? "BigInt.zero()"
          : asType === "bool" ? "false"
          : asType === "f64" ? "0.0"
          : "0";
        lines.push(`  ${f.name}: ${asType} = ${defaultVal};`);
      }
    }
    lines.push("");
    lines.push("  constructor(id: string) {");
    lines.push("    this.id = id;");
    lines.push("  }");
    lines.push("");

    // static load(id: string): Entity | null
    lines.push(`  static load(id: string): ${entityName} | null {`);
    lines.push(`    const raw = store.get("${entityName}", id);`);
    lines.push(`    if (raw.length == 0) return null;`);
    lines.push(`    const entity = new ${entityName}(id);`);
    for (const f of fields) {
      if (f.name === "id" || f.isDerived) continue;
      const asType = graphqlTypeToAs(f.type);
      if (asType === "string") {
        lines.push(`    entity.${f.name} = extractJsonField(raw, "${f.name}");`);
      } else if (asType === "BigInt") {
        lines.push(`    entity.${f.name} = BigInt.fromString(extractJsonField(raw, "${f.name}"));`);
      } else if (asType === "bool") {
        lines.push(`    entity.${f.name} = extractJsonField(raw, "${f.name}") == "true";`);
      } else if (asType === "i32") {
        lines.push(`    {`);
        lines.push(`      const valStr = extractJsonField(raw, "${f.name}");`);
        lines.push(`      if (valStr.length > 0) entity.${f.name} = parseInt(valStr) as i32;`);
        lines.push(`    }`);
      } else if (asType === "f64") {
        lines.push(`    {`);
        lines.push(`      const valStr = extractJsonField(raw, "${f.name}");`);
        lines.push(`      if (valStr.length > 0) entity.${f.name} = parseFloat(valStr);`);
        lines.push(`    }`);
      }
    }
    lines.push("    return entity;");
    lines.push("  }");
    lines.push("");

    // static remove(id: string): void
    lines.push(`  static remove(id: string): void {`);
    lines.push(`    store.remove("${entityName}", id);`);
    lines.push("  }");
    lines.push("");

    // save(): void
    lines.push("  save(): void {");
    const jsonParts: string[] = [];
    for (const f of fields) {
      if (f.isDerived) continue; // Skip virtual reverse-lookup relations in database payload
      const asType = graphqlTypeToAs(f.type);
      if (asType === "BigInt" || asType === "string") {
        jsonParts.push(`"\\"${f.name}\\":\\"" + this.${f.name}.toString() + "\\""`);
      } else {
        jsonParts.push(`"\\"${f.name}\\":" + this.${f.name}.toString()`);
      }
    }
    lines.push(`    const payload = "{" + ${jsonParts.join(' + "," + ')} + "}";`);
    lines.push(`    store.set("${entityName}", this.id, payload);`);
    lines.push("  }");
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Command
// ---------------------------------------------------------------------------

export function codegenCommand(): Command {
  const cmd = new Command("codegen");

  cmd
    .description("Generate typed AssemblyScript bindings from ABI files and schema.graphql")
    .action(() => {
      const projectDir = process.cwd();
      const configPath = path.join(projectDir, "logrix.yaml");

      if (!fs.existsSync(configPath)) {
        console.error("Error: logrix.yaml not found. Run this command from your project root.");
        process.exit(1);
      }

      const config: LogrixConfig = parseYaml(fs.readFileSync(configPath, "utf-8")) as LogrixConfig;

      const generatedDir = path.join(projectDir, "src", "generated");
      fs.mkdirSync(generatedDir, { recursive: true });

      console.log("Generating src/generated/events.ts ...");
      const eventsTs = generateEventsTs(config.dataSources, projectDir);
      fs.writeFileSync(path.join(generatedDir, "events.ts"), eventsTs);

      console.log("Generating src/generated/schema.ts ...");
      const schemaTs = generateSchemaTs(projectDir);
      fs.writeFileSync(path.join(generatedDir, "schema.ts"), schemaTs);

      console.log("Done.");
    });

  return cmd;
}
